### ISSUE TITLE
Global emotes display as boxes in console

### ISSUE THREAD

**Issue by kasamikona** [kasamikona/ConsoleChat#4]
Global emotes are converted to unicode emoji, which cannot be displayed in the console.

**Comment by Natemo2625** [comment]
using this on repl.it and i can see them

**Comment by kasamikona** [comment]
The intention with this was to actively replace global emotes with some text replacement, since many of those friends using it are using simpler console/terminal programs that don't support emoji. As I mentioned in your issue #8 I'm no longer working on this so I won't be making any changes to emote handling.
