### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Natemo2625** [kasamikona/ConsoleChat#8]
Can you DM with this?

**Comment by kasamikona** [comment]
Hi, I didn't realize anyone was using this. It was a messy tool that was only really meant for me and a few friends and I made it public for convenience, but it's now an abandoned project. I don't plan to update it in the future if a major discord.js update breaks it, so please don't rely on it.

I don't think it's able to do DMs explicitly, and I don't plan to add that feature or any other new features. Sorry if this impacts your plans. You're welcome to try and add it yourself, but I know the code is a big mess so I wouldn't personally recommend it.

**Comment by Natemo2625** [comment]
oh ok, i guess i could try to add it myself. my main plan was to have a way to access discord whenever its blocked and so far this does just that

**Comment by Natemo2625** [comment]
@kasamikona if there were to be a major update to discord.js and I updated the code, would you add it here if I opened a pull request? Just wondering since I've heard about discord.js v13

**Comment by Natemo2625** [comment]
also one last question, can i set a server and channel to connect to by default with their ids?

**Comment by kasamikona** [comment]
I'll probably archive this repo so I won't be able to accept PRs, if you want to maintain your own updated fork that's fine with me. I might link to yours if you're okay with that.

There's no direct way to set a default channel but you can just use
```js
let defaultConsoleChannel = client.channels.fetch(yourDefaultChannelId);
consoleChat.setChannel(defaultConsoleChannel);
```
when your bot starts. No server id is necessary when using channel ids directly.

**Comment by Natemo2625** [comment]
Ah ok, thanks. And yes I'll be fine with you linking to my [fork](https://github.com/Natemo6348/ConsoleChat).

**Comment by Natemo2625** [comment]
```
let defaultConsoleChannel = client.channels.fetch(yourDefaultChannelId);
consoleChat.setChannel(defaultConsoleChannel);
```
did not work, got this error
```
node index.js
Running ConsoleChat.js v1.2.3
readline.js:1147
            throw err;
            ^

TypeError: consoleMsgChannel.send is not a function
    at sendMessage (/home/runner/ConsoleChat/consoleChat.js:102:23)
    at processCommand (/home/runner/ConsoleChat/consoleChat.js:452:44)
    at Interface.<anonymous> (/home/runner/ConsoleChat/consoleChat.js:201:23)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._line (readline.js:658:8)
    at Interface._ttyWrite (readline.js:1003:14)
    at ReadStream.onkeypress (readline.js:205:10)
    at ReadStream.emit (events.js:315:20)
    at emitKeys (internal/readline/utils.js:335:14)
exit status 1
```

**Comment by Natemo2625** [comment]
yes i did change it to the channel id

EDIT: fixed

**Comment by kasamikona** [comment]
My bad, channels.fetch returns a channel promise not the channel itself.
